services:
  # 1. MySQL (Í∏∞Ï°¥)
  mock-mysql:
    image: mysql:8.0
    container_name: mock-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mockpay
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  # 2. Redis (Í∏∞Ï°¥)
  mock-redis:
    image: redis:7.2
    container_name: mock-redis
    ports:
      - "6379:6379"

  # üëá [Ï∂îÍ∞Ä] 3. Zookeeper (Kafka Í¥ÄÎ¶¨Ïûê)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: mock-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # üëá [Ï∂îÍ∞Ä] 4. Kafka (Î©îÏãúÏßÄ ÌÅê)
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: mock-kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1